# Cron job to run Cult model on Ellie at 18:40 GMT (00:10 IST)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ellie-cult-cron
spec:
  schedule: "10 19 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ellie-cult-cron-depl
              image: gagangoku1/ellie-cult-cron:latest
