# docker run -itd -e POSTGRES_USER=gagan -e POSTGRES_PASSWORD=gagan -p 5432:5432 -v /data:/var/lib/postgresql/data postgres:14.2

# From https://www.airplane.dev/blog/deploy-postgres-on-kubernetes
# To avoid this error:
# failed to generate container "xxx" spec: failed to generate spec: failed to mkdir "/mnt/data": mkdir /mnt/data: read-only file system
# use /var/lib/data instead of /mnt/data

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume6
  labels:
    type: local
    app: postgres
spec:
  storageClassName: fast
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim6
  labels:
    app: postgres
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi  # Sets volume size

---
# Deployment (not using statefulsets)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.2
          # In case you need to ssh into the container without starting postgres
          # command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          args: ["-c", "max_connections=500", "-c", "shared_buffers=512MB"]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            # NOTE: Dont override PGDATA. Postgres internally declares VOLUME and it will automatically get assigned to a persistent volume
            - name: POSTGRES_DB
              value: noti
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim6
---

# Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: postgres
